dist: trusty

language: java
jdk:
  - oraclejdk8

services:
  - postgresql
addons:
  postgresql: "9.5"

install: true

before_install:
  - psql -c 'create database "github_developers";' -U postgres

script:
  - chmod +x ./.ci/script.sh 
  - ./.ci/script.sh